### ISSUE TITLE
Download unsuccessful

### ISSUE THREAD

**Issue by petersem** [cgnetwork/trailarr#3]
Trailer download did not complete. 

steps:
- searched for 'Dune'
- selected latest dune version
- clicked download

Expected
- trailer would download 

Experienced
- button changed to 'downloading', but never changed after 20 minutes
- no trailer downloaded to trailer volume, specified in yaml

**Comment by trueChazza** [comment]
Hi, thanks for opening the bug issue.

I have since tested and all is working. Could you please try again with the latest build and see if it works for you?

**Comment by trueChazza** [comment]
https://github.com/cgnetwork/trailarr/blob/master/README.md

Note: trailers are downloaded to the `trailers` directory in the latest build.
