### ISSUE TITLE
Help needed: understanding path

### ISSUE THREAD

**Issue by snickers2k** [cgnetwork/trailarr#8]
Hey.
Seems to be a great project.

But what exactly did you mean by "path/to/trailers" ? I have no direct trailers Path, instead the trailers are packed in the movie-folders, just like plex is requesting it.

So did you mean "path/to/movies" ? 

just want to clarify this, before my movies folder gets deleted or something^^

thanks for your work and for sharing it

**Comment by trueChazza** [comment]
Hi, thanks for your question.

I agree - `path/to/trailers` is unclear as to whether it means a path to all the trailers on a host (nested in sub directories), or a path with trailers at the root.

The path is where the trailers will be downloaded to.

So for example, if your setup is `/movies/some-movie`, and you mount your `/movies` path - trailers will be downloaded to the root of `/movies`.

So I think - `path/to/download` better describes the host path. What do you think?

**Comment by trueChazza** [comment]
Also just to clarify - the application does not delete any directories or files.

Even if you mounted your `/movies` directory, it will only download trailers to the root of that directory.

**Comment by snickers2k** [comment]
hey. thanks for your response.

yes, path/to/download is more convenient i guess. 

so i guess i have to wait for the "plex integration" feature request for me to use it.

i was hoping trailarr could already take the Paths out of Sonarr/Radarr, like bazarr does it (because usually other "'arr" or "Starr" apps are companion apps)
but i saw the feature-request for fetching the movie-folder-path from plex itself, which would be great aswell.

i'll test it anyway :) looks really promising 👍
